version: 2
updates:
  # Note: Go version and golangci-lint version updates are handled by Renovate
  # See renovate.json5 for configuration
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      k8s-deps:
        patterns:
          - "k8s.io/api" # a single dependency name
          - "k8s.io/apimachinery"
          - "k8s.io/client-go"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: pip
    directory: /docs
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /ui/components-lib
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /ui/dashboard
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /ui/extension
    schedule:
      interval: daily
