apiVersion: promoter.argoproj.io/v1alpha1
kind: ControllerConfiguration
metadata:
  labels:
    app.kubernetes.io/name: promoter
    app.kubernetes.io/part-of: promoter
    app.kubernetes.io/managed-by: kustomize
  name: controller-configuration
spec:
  promotionStrategy:
    workQueue:
      maxConcurrentReconciles: 10
      requeueDuration: "5m"
      rateLimiter:
        maxOf:
          - bucket:
              qps: 10
              bucket: 100
          - fastSlow:
              fastDelay: "1s"
              slowDelay: "5m"
              maxFastAttempts: 3
  changeTransferPolicy:
    workQueue:
      maxConcurrentReconciles: 10
      requeueDuration: "5m"
      rateLimiter:
        maxOf:
          - bucket:
              qps: 10
              bucket: 100
          - fastSlow:
              fastDelay: "1s"
              slowDelay: "5m"
              maxFastAttempts: 3
  pullRequest:
    workQueue:
      maxConcurrentReconciles: 10
      requeueDuration: "5m"
      rateLimiter:
        maxOf:
          - bucket:
              qps: 10
              bucket: 100
          - fastSlow:
              fastDelay: "1s"
              slowDelay: "5m"
              maxFastAttempts: 3
    template:
      title: "Promote {{ trunc 5 .ChangeTransferPolicy.Status.Proposed.Dry.Sha }} to `{{ .ChangeTransferPolicy.Spec.ActiveBranch }}`"
      description: "This PR is promoting the environment branch `{{ .ChangeTransferPolicy.Spec.ActiveBranch }}` which is currently on dry sha {{ .ChangeTransferPolicy.Status.Active.Dry.Sha }} to dry sha {{ .ChangeTransferPolicy.Status.Proposed.Dry.Sha }}."
  commitStatus:
    workQueue:
      maxConcurrentReconciles: 10
      requeueDuration: "5m"
      rateLimiter:
        maxOf:
          - bucket:
              qps: 10
              bucket: 100
          - fastSlow:
              fastDelay: "1s"
              slowDelay: "5m"
              maxFastAttempts: 3
  argocdCommitStatus:
    watchLocalApplications: true
    workQueue:
      maxConcurrentReconciles: 10
      requeueDuration: "5m"
      rateLimiter:
        maxOf:
          - bucket:
              qps: 10
              bucket: 100
          - fastSlow:
              fastDelay: "1s"
              slowDelay: "5m"
              maxFastAttempts: 3
  timedCommitStatus:
    workQueue:
      maxConcurrentReconciles: 10
      requeueDuration: "5m"
      rateLimiter:
        maxOf:
          - bucket:
              qps: 10
              bucket: 100
          - fastSlow:
              fastDelay: "1s"
              slowDelay: "5m"
              maxFastAttempts: 3
  gitCommitStatus:
    workQueue:
      maxConcurrentReconciles: 10
      requeueDuration: "5m"
      rateLimiter:
        maxOf:
          - bucket:
              qps: 10
              bucket: 100
          - fastSlow:
              fastDelay: "1s"
              slowDelay: "5m"
              maxFastAttempts: 3
