argocd:
  upstream: https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install-with-hydrator.yaml

gitops-promoter:
  upstream: https://github.com/argoproj-labs/gitops-promoter/releases/download/v0.21.0/install.yaml
