## Append samples of your project ##
resources:
- promoter_v1alpha1_pullrequest.yaml
- promoter_v1alpha1_commitstatus.yaml
- promoter_v1alpha1_revertcommit.yaml
- promoter_v1alpha1_proposedcommit.yaml
- promoter_v1alpha1_promotionstrategy.yaml
- promoter_v1alpha1_scmprovider.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
