resources:
- promoter_v1alpha1_pullrequest.yaml
- promoter_v1alpha1_commitstatus.yaml
- promoter_v1alpha1_revertcommit.yaml
- promoter_v1alpha1_promotionstrategy.yaml
- promoter_v1alpha1_scmprovider.yaml
- promoter_v1alpha1_gitrepository.yaml
- promoter_v1alpha1_changetransferpolicy.yaml
- promoter_v1alpha1_argocdcommitstatus.yaml
- promoter_v1alpha1_controllerconfiguration.yaml
- promoter_v1alpha1_clusterscmprovider.yaml
- promoter_v1alpha1_timedcommitstatus.yaml
- promoter_v1alpha1_gitcommitstatus.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
