resources:
- ../default

images:
- name: quay.io/argoprojlabs/gitops-promoter
  newName: quay.io/argoprojlabs/gitops-promoter
  newTag: v0.20.3
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
