# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/promoter.argoproj.io_pullrequests.yaml
- bases/promoter.argoproj.io_commitstatuses.yaml
- bases/promoter.argoproj.io_revertcommits.yaml
- bases/promoter.argoproj.io_promotionstrategies.yaml
- bases/promoter.argoproj.io_scmproviders.yaml
- bases/promoter.argoproj.io_gitrepositories.yaml
- bases/promoter.argoproj.io_changetransferpolicies.yaml
- bases/promoter.argoproj.io_argocdcommitstatuses.yaml
- bases/promoter.argoproj.io_controllerconfigurations.yaml
- bases/promoter.argoproj.io_clusterscmproviders.yaml
- bases/promoter.argoproj.io_timedcommitstatuses.yaml
- bases/promoter.argoproj.io_gitcommitstatuses.yaml
# +kubebuilder:scaffold:crdkustomizeresource

patches:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
# +kubebuilder:scaffold:crdkustomizewebhookpatch

# [WEBHOOK] To enable webhook, uncomment the following section
# the following config is for teaching kustomize how to do kustomization for CRDs.
#configurations:
#- kustomizeconfig.yaml
