# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/promoter.argoproj.io_pullrequests.yaml
- bases/promoter.argoproj.io_commitstatuses.yaml
- bases/promoter.argoproj.io_revertcommits.yaml
- bases/promoter.argoproj.io_promotionstrategies.yaml
- bases/promoter.argoproj.io_scmproviders.yaml
- bases/promoter.argoproj.io_gitrepositories.yaml
- bases/promoter.argoproj.io_changetransferpolicies.yaml
- bases/promoter.argoproj.io_argocdcommitstatuses.yaml
- bases/promoter.argoproj.io_controllerconfigurations.yaml
- bases/promoter.argoproj.io_clusterscmproviders.yaml
- bases/promoter.argoproj.io_timedcommitstatuses.yaml
- bases/promoter.argoproj.io_gitcommitstatuses.yaml
#+kubebuilder:scaffold:crdkustomizeresource

patches:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
#- path: patches/webhook_in_pullrequests.yaml
#- path: patches/webhook_in_commitstatuses.yaml
#- path: patches/webhook_in_revertcommits.yaml
#- path: patches/webhook_in_promotionstrategies.yaml
#- path: patches/webhook_in_scmproviders.yaml
#- path: patches/webhook_in_gitrepositories.yaml
#- path: patches/webhook_in_changetransferpolicies.yaml
#+kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable cert-manager, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
#- path: patches/cainjection_in_pullrequests.yaml
#- path: patches/cainjection_in_commitstatuses.yaml
#- path: patches/cainjection_in_revertcommits.yaml
#- path: patches/cainjection_in_promotionstrategies.yaml
#- path: patches/cainjection_in_scmproviders.yaml
#- path: patches/cainjection_in_gitrepositories.yaml
#- path: patches/cainjection_in_changetransferpolicies.yaml
#+kubebuilder:scaffold:crdkustomizecainjectionpatch

# [WEBHOOK] To enable webhook, uncomment the following section
# the following config is for teaching kustomize how to do kustomization for CRDs.

#configurations:
#- kustomizeconfig.yaml
