name: ci-nilaway
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}
jobs:
  ci:
#    strategy:
#      fail-fast: false
#      matrix:
#        kubernetes-minor-version:
#          - 1.29.0
#          - 1.30.0
#          - 1.31.0
    name: Check Nilaway
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout Repo
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # pin@v4
      - name: Set up Go
        uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # pin@v5
        with:
          go-version: "1.24"
      - name: Nilaway
      - run: make nilaway-no-test


