name: Spelling

permissions:
  contents: read

on: 
  pull_request
    paths:
      - 'docs/**'
      - '*.md'
      - 'README.md'
      - '.github/workflows/spelling.yaml' 

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}
  timeout-minutes: 10

env:
  CLICOLOR: 1

jobs:
  spelling:
    name: Spell Check with Typos
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Actions Repository
      uses: actions/checkout@v6@de0fac2e4500dabe0009e67214ff5f5447ce83dd
    - name: Spell Check Repo
      uses: crate-ci/typos@v1.42.0